services:
  cmprovision:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBUG_APP: ${DEBUG_APP:-0}
        DEBUG_PORT: ${DEBUG_PORT:-5678}

    container_name: cmprovision
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./conf:/app/conf
      - ./scriptexecute:/tftpboot
      - ./images:/uploads
      - ./results:/app/results
      - ./eeproms:/eeproms
    environment:
      - TZ=Europe/Paris
      - DEBUG_APP=${DEBUG_APP:-0}
      - DEBUG_PORT=${DEBUG_PORT:-5678}
