services:
  cmprovision:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBUG_APP: ${DEBUG_APP:-0}
        DEBUG_PORT: ${DEBUG_PORT:-5678}

    container_name: cmprovision
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./conf:/app/conf
      - ./scriptexecute:/tftpboot
      - ./images:/uploads
      - ./results:/app/results
      - ./eeproms:/eeproms
      # Bind mount for localtime to ensure correct timezone
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      - DEBUG_APP=${DEBUG_APP:-0}
      - DEBUG_PORT=${DEBUG_PORT:-5678}
